name: Build, Test and Publish Executable

on:
  push:
    branches-ignore:
      - master

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      
    - name: Ensure GitHub NuGet Source
      run: dotnet nuget add source https://nuget.pkg.github.com/agents-net/index.json -n agents-net -u bearer -p ${{ secrets.PACKAGE_ACCESS_TOKEN }} --store-password-in-clear-text
      
    - name: Build with dotnet
      run: dotnet build src --configuration Release
      
  test:
  
    name: test
    runs-on: windows-latest
    needs: build
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
          
    - name: Ensure GitHub NuGet Source
      run: dotnet nuget add source https://nuget.pkg.github.com/agents-net/index.json -n agents-net -u bearer -p ${{ secrets.PACKAGE_ACCESS_TOKEN }} --store-password-in-clear-text
      
    - name: Test with dotnet
      run: dotnet test src --configuration Release
      
  publish:

    runs-on: windows-latest
    needs: build

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      
    - name: Ensure GitHub NuGet Source
      run: dotnet nuget add source https://nuget.pkg.github.com/agents-net/index.json -n agents-net -u bearer -p ${{ secrets.PACKAGE_ACCESS_TOKEN }} --store-password-in-clear-text
          
    - name: Purge old artifacts
      uses: kolpav/purge-artifacts-action@v1
      with:
        token: ${{ secrets.PACKAGE_ACCESS_TOKEN }}
        expire-in: 0 #will purge immediately
      
    - name: Publish single executable artifact
      run: dotnet publish src\Agents.Net.LogViewer\Agents.Net.LogViewer.csproj -r win-x64 -o publish -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:PublishReadyToRun=true --self-contained true --configuration Release
      
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: executable
        path: |
          publish/*
          !publish/*.pdb